[project]
name = "delta-virtual"
version = "0.1.0"
description = "demo data generator"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "deltalake>=1.4.2",
    "faker>=40.4.0",
    "pandas>=3.0.1",
    "pyarrow>=23.0.1",
]
